package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment().dao();
}
