package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseAutoReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoReply extends BaseAutoReply<AutoReply> {
	public static final AutoReply dao = new AutoReply().dao();
}
