package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseCustomMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomMenu extends BaseCustomMenu<CustomMenu> {
	public static final CustomMenu dao = new CustomMenu().dao();
}
