package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keyword extends BaseKeyword<Keyword> {
	public static final Keyword dao = new Keyword().dao();
}
