package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseMaterialImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialImage extends BaseMaterialImage<MaterialImage> {
	public static final MaterialImage dao = new MaterialImage().dao();
}
