package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseMaterialFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialFile extends BaseMaterialFile<MaterialFile> {
	public static final MaterialFile dao = new MaterialFile().dao();
}
