package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseMaterialNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialNews extends BaseMaterialNews<MaterialNews> {
	public static final MaterialNews dao = new MaterialNews().dao();
}
