package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BaseMaterialText;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialText extends BaseMaterialText<MaterialText> {
	public static final MaterialText dao = new MaterialText().dao();
}
