package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BasePublic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Public extends BasePublic<Public> {
	public static final Public dao = new Public().dao();
}
