package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BasePublicTags;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicTags extends BasePublicTags<PublicTags> {
	public static final PublicTags dao = new PublicTags().dao();
}
