package me.moe.modules.weixin.model;

import me.moe.modules.weixin.model.base.BasePublicFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicFollow extends BasePublicFollow<PublicFollow> {
	public static final PublicFollow dao = new PublicFollow().dao();
}
