package me.moe.modules.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialImage<M extends BaseMaterialImage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCoverId(java.lang.Integer coverId) {
		set("cover_id", coverId);
	}

	public java.lang.Integer getCoverId() {
		return get("cover_id");
	}

	public void setCoverUrl(java.lang.String coverUrl) {
		set("cover_url", coverUrl);
	}

	public java.lang.String getCoverUrl() {
		return get("cover_url");
	}

	public void setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
	}

	public java.lang.String getMediaId() {
		return get("media_id");
	}

	public void setWechatUrl(java.lang.String wechatUrl) {
		set("wechat_url", wechatUrl);
	}

	public java.lang.String getWechatUrl() {
		return get("wechat_url");
	}

	public void setManagerId(java.lang.Integer managerId) {
		set("manager_id", managerId);
	}

	public java.lang.Integer getManagerId() {
		return get("manager_id");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setIsUse(java.lang.Integer isUse) {
		set("is_use", isUse);
	}

	public java.lang.Integer getIsUse() {
		return get("is_use");
	}

}
